name: Picota-Frontend

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 17.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 17.8.0
      - name: Install dependencies
        run: npm install    
      # - name: Test
      #   run: npm test
      #   env:
      #     CI: true
      - name: Generate build
        run: npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  
  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    environment: picota-dev
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: aws s3 sync . s3://react-github-actions --acl public-read
        working-directory: build
  