name: Picota-Frontend

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 17.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 17.8.0
      - name: Install dependencies
        run: npm install    
      # - name: Test
      #   run: npm test
      #   env:
      #     CI: true
      - name: Generate build
        run: npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: build-dev
          path: build
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment: picota-dev
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: build-dev
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        run: aws s3 sync ./ s3://picota-bucket-frontend-dev --delete
        working-directory: .
  